### PR TITLE
ansible modules need to be python 2.4 compatible

### PR DESCRIPTION
**Pull request by fooelisa**

### CODE REVIEW

**Comment by dbarrosop** [comment]
This self merging PR's have to really stop...  :(

Do you realize that this PR breaks python3 support, right? And I would rather work towards python3 support instead of going backwards and ensuring python2.4 support. It's 2016.

**Comment by ktbyers** [comment]
Yes, my vote would be NAPALM supports Python2.7 (and then work on adding Python3 support). Even supporting Python2.6 is pretty questionable. I still have this support in Netmiko (Py2.6), but am probably going to drop it.

**Comment by fooelisa** [comment]
So this is because I submitted a PR to include the modules into ansible-modules-extras, a number of changes were related to getting the modules compliant with their requirements. Amongst others, they enforce 2.4 support.

https://github.com/ansible/ansible-modules-extras/pull/1697 

Sorry for the self merging, no one has looked at the ansible modules in a while, so I was just going ahead  with what it takes to get them in there.

**Comment by ktbyers** [comment]
@fooelisa @dbarrosop Is it worth it to submit to ansible-modules-extras? I have less than zero interest in supporting Python 2.4 or Python 2.5. 

The modules also are not going to work on Python 2.4 or Python 2.5 since the underlying libraries won't generally support these version of Python.

This also requirement doesn't really make sense in our context since we run everything in 'connection: local' mode (i.e. it should be pretty easy to get the Ansible control machine to a reasonable version of Python). 

FYI, Ansible itself (on the control machine) only supports Py2.6 and Py2.7.

**Comment by dbarrosop** [comment]
I agree with you. I am actually against ansible's way of adding third party
modules. Seems as if they wanted to own everything. I would rather have a
model like stackstorm where they allow you to install packs from your own
repo. I also agree with not supporting older versions of Python. We should
aim 2.7 and 3.x. I don't care about the rest. I doubt anyone is actually
using anything older.

**Pull request merged**
