### PR TITLE
Prepending napalm facts with napalm_; moving get_facts to be direct 

### PR DESCRIPTION
**Pull request by ktbyers**
Also added changes to napalm_validate to cause Ansible failure if the validation fails.

### CODE REVIEW

**Comment by ktbyers** [comment]
Fixes:  https://github.com/napalm-automation/napalm-ansible/issues/73

**Comment by ktbyers** [comment]
Here is test output with `filters` of facts, bgp_neighbors, and interfaces:

```
ok: [pynet-rtr1] => {
    "ansible_facts": {
        "napalm_bgp_neighbors": {
            "global": {
                "peers": {
                    "10.220.88.38": {
                        "address_family": {
                            "ipv4": {
                                "accepted_prefixes": 0, 
                                "received_prefixes": 0, 
                                "sent_prefixes": 0
                            }
                        }, 
                        "description": "", 
                        "is_enabled": true, 
                        "is_up": true, 
                        "local_as": 42, 
                        "remote_as": 44, 
                        "remote_id": "10.220.88.38", 
                        "uptime": 14083200
                    }
                }, 
                "router_id": "10.220.88.20"
            }
        }, 
        "napalm_facts": {
            "fqdn": "pynet-rtr1.twb-tech.com", 
            "hostname": "pynet-rtr1", 
            "interface_list": [
                "FastEthernet0", 
                "FastEthernet1", 
                "FastEthernet2", 
                "FastEthernet3", 
                "FastEthernet4", 
                "Vlan1"
            ], 
            "model": "881", 
            "os_version": "C880 Software (C880DATA-UNIVERSALK9-M), Version 15.4(2)T1, RELEASE SOFTWARE (fc3)", 
            "serial_number": "FTX1512038X", 
            "uptime": 34893540, 
            "vendor": "Cisco"
        }, 
        "napalm_fqdn": "pynet-rtr1.twb-tech.com", 
        "napalm_hostname": "pynet-rtr1", 
        "napalm_interface_list": [
            "FastEthernet0", 
            "FastEthernet1", 
            "FastEthernet2", 
            "FastEthernet3", 
            "FastEthernet4", 
            "Vlan1"
        ], 
        "napalm_interfaces": {
            "FastEthernet0": {
                "description": "", 
                "is_enabled": true, 
                "is_up": false, 
                "last_flapped": -1.0, 
                "mac_address": "C8:9C:1D:EA:0E:B2", 
                "speed": 100
            }, 
            "FastEthernet1": {
                "description": "", 
                "is_enabled": true, 
                "is_up": false, 
                "last_flapped": -1.0, 
                "mac_address": "C8:9C:1D:EA:0E:B3", 
                "speed": 100
            }, 
            "FastEthernet2": {
                "description": "", 
                "is_enabled": true, 
                "is_up": false, 
                "last_flapped": -1.0, 
                "mac_address": "C8:9C:1D:EA:0E:B4", 
                "speed": 100
            }, 
            "FastEthernet3": {
                "description": "", 
                "is_enabled": true, 
                "is_up": false, 
                "last_flapped": -1.0, 
                "mac_address": "C8:9C:1D:EA:0E:B5", 
                "speed": 100
            }, 
            "FastEthernet4": {
                "description": "*** LAN connection (don't change) ***", 
                "is_enabled": true, 
                "is_up": true, 
                "last_flapped": -1.0, 
                "mac_address": "C8:9C:1D:EA:0E:B6", 
                "speed": 100
            }, 
            "Vlan1": {
                "description": "", 
                "is_enabled": true, 
                "is_up": false, 
                "last_flapped": -1.0, 
                "mac_address": "C8:9C:1D:EA:0E:B2", 
                "speed": 100
            }
        }, 
        "napalm_model": "881", 
        "napalm_os_version": "C880 Software (C880DATA-UNIVERSALK9-M), Version 15.4(2)T1, RELEASE SOFTWARE (fc3)", 
        "napalm_serial_number": "FTX1512038X", 
        "napalm_uptime": 34893540, 
        "napalm_vendor": "Cisco"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "args": null, 
            "dev_os": "ios", 
            "filter": [
                "facts", 
                "interfaces", 
                "bgp_neighbors"
            ], 
            "hostname": "cisco1.twb-tech.com", 
            "ignore_notimplemented": false, 
            "optional_args": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": null, 
            "timeout": 60, 
            "username": "pyclass"
        }
    }
}
```

**Comment by dbarrosop** [comment]
LGTM, we could probably merge after #79 and try the self-deployment feature?

**Comment by ktbyers** [comment]
Sounds good. 

We should just make clear in the release_notes that it has a backwards incompatible change (i.e. we have renamed our facts to prepend with `napalm_`.

**Comment by dbarrosop** [comment]
We will have to rebase this one

**Comment by ktbyers** [comment]
Replaced by PR #81 

...that fixes the rebase issue.

**Pull request closed without merging**
