### PR TITLE
update no log on provider to only capture password

### PR DESCRIPTION
**Pull request by itdependsnetworks**

### CODE REVIEW

**Comment by ktbyers** [comment]
@itdependsnetworks Can you expand this pattern to also include `optional_args['secret']` to be no_log (if someone passes secret in this way?

**Comment by itdependsnetworks** [comment]
@ktbyers updated.

**Comment by ktbyers** [comment]
@itdependsnetworks This looks good, but want to merge/review PR #66 first.

**Comment by dbarrosop** [comment]
@itdependsnetworks would you mind rebasing? that should introduce testing and fix the CI :)

**Pull request merged**
