### PR TITLE
check_mode support for get_facts

### PR DESCRIPTION
**Pull request by fooelisa**
when --check, device connection will be established but no data retrieved

### CODE REVIEW

**Comment by XioNoX** [comment]
This PR seems to go against how it works by default in Ansible. Running ansible with --check will always connect to the target server and retrieves facts, but will not make changes.

In my current workflow, when I run ansible in check mode (--check) the playbook will: 
- gather facts from the devices
- generate a configuration
- send the configuration to the device for a diff (without any commit)
  Then we review the changes and run it once more without --check if everything is fine
  --check is thus a global sign of "don't worry, you're not going to break anything".

**Comment by fooelisa** [comment]
Hm, that makes sense

**Comment by dbarrosop** [comment]
I don't fully get the purpose of this module. Is it a get_facts or a wrapper for getters? Wouldn't be better to just have a module for every getter? The name is misleading.

And I agree with @XioNoX, gathering info should be done always as you might need that info to feed another module.

**Comment by fooelisa** [comment]
Initially it was separate modules, which I re-did into one based on feedback from @privateip, which is more in-line with the ansible world. Also, this way we are able to fetch various pieces of information with a single device connection, vs. having to re-connect for each call.

**Pull request merged**
