### PR TITLE
Removed exception when SSH connection closes abnormally

### PR DESCRIPTION
**Pull request by austind**
Verified this change fixes a problem where playbooks that use SSH proxies fail (ProxyCommand directives in ~/.ssh/config)

### CODE REVIEW

**Comment by ktbyers** [comment]
@dbarrosop Any objections to this?

I think this is the right behavior i.e. that the module shouldn't fail if the connection close fails. In other words, we try to gracefully close the connection, but if the connection close fails...we keep moving on.

**Comment by ktbyers** [comment]
We should make sure this is done for all the Ansible modules that this pattern applies to (not just napalm_get_facts).

**Comment by austind** [comment]
I'm not clear as to what failed in travis; the errors cited don't appear to relate to closing connections

**Comment by ktbyers** [comment]
Yep, that looks right.

**Comment by ktbyers** [comment]
This looks all good...just want to verify with @dbarrosop that he agrees with this change and it should be ready to go.

**Comment by dbarrosop** [comment]
I don’t think this is a good idea. In my experience failing to close a connection means something broke. Otherwise, why would it fail? I think it’s extremely safer to fail and let the user handle the error in a bloc..rescue construct in ansible. If the error has to be ignored for some sane reason (I am sure there are legit reasons to ignore this error) that logic should be handled in the driver and avoid raising the exception to begin with instead of swallowing all exceptions for all the drivers.

**Comment by austind** [comment]
@dbarrosop I agree, this approach does seem heavy-handed

@ktbyers Based on the trace, it looks like the `os.kill()` call fails. I wonder if this is trying to kill a process on my local machine, not on the jumphost? Not sure how paramiko handles proxied connections

**Comment by austind** [comment]
Let me do some more testing and I'll report back

**Comment by ktbyers** [comment]
Right now (I think) it is failing because there is a race condition between two events i.e. the SSH connection did close properly ('exit' via Netmiko), but after that we try to cleanup some other object and Paramiko says we can't do this as the SSH process is already gone (the process was already cleaned up).

Also the SSH connection will be closed when the process ends at the OS level...though in a non-graceful exit it might persist until it is purged at a TCP timer level (or worse case the VTY timer).

In general, I don't like adding extra logic into playbooks (i.e. I try to keep as much logic out of playbooks as possible).

I could also potentially fix in Netmiko i.e. add a try/except OSError statement on this one failing object...which I think would be pretty delimited to this context (I say this based on some experiments I just did).

**Comment by dbarrosop** [comment]
> In general, I don't like adding extra logic into playbooks (i.e. I try to keep as much logic out of playbooks as possible).

I do agree but we can't take an executive decision like this on behalf of everybody. I'd be very pissed if my code was failing to detect issues because someone decided to put on their lib something like:

```
try:
    # code that can fail
except:
    pass
```

I'd rather get a `ProxyConnectionCloseError` type of exception so I can decide if I want to swallow it or not myself. In any case, the ansible module affects many other drivers and many other potential scenarios so I think this specific should be handled either in netmiko or in the driver.

Aslo, this sentence of yours gave me an idea:

> In general, I don't like adding extra logic into playbooks (i.e. I try to keep as much logic out of playbooks as possible).

We could have an "ignore_errors" attribute where we can pass something like:

```
{ "eos": ["pyeapi.exceptions.SillyException"], "ios": ["netmiko.ConnectionCloseError", "netmiko.SomeOtherError"]}
```

And swallow those specific exceptions for those specific drivers.

**Comment by ktbyers** [comment]
Okay, I fixed this here:

https://github.com/ktbyers/netmiko/commit/facc47ab68fe65fb8a9702b590e8fc487aad60eb

@austind Can you test the netmiko develop branch and see if it fixes your issue?

I am going to go ahead and close this as it sounds like we are going to fix it on the Netmiko side.

**Pull request closed without merging**
