### PR TITLE
added ping module

### PR DESCRIPTION
**Pull request by jedelman8**
Ping module for Ansible using NAPALM `ping` method.

### CODE REVIEW

**Comment by dbarrosop** [comment]
Cool! I wonder if we could generalize this so it can also execute the `traceroute` method and potentially others with a similar scope. What do you think?

**Comment by jedelman8** [comment]
I'd rather see a separate module for `traceroute` personally...however, one thing I'm thinking about here :

Normalizing the key used regardless if success or error.

Today it's this:

```
# when echo request succeeds
  "{"success": {"packet_loss": 0, "probes_sent": 2,
           "results": [{"ip_address": "10.0.0.5:", "rtt": 1.71},
            {"ip_address": "10.0.0.5:", "rtt": 0.733}],
            "rtt_avg": 1.225, "rtt_max": 1.718, "rtt_min": 0.733,
            "rtt_stddev": 0.493}}
   # when echo request fails
   {"error": "connect: Network is unreachable\n"}}
```

I'd rather see a `status` key that has **success** or **error** as values.  Then a `msg` key for the error message and `results` for the dict of results.  What are your thoughts?

**Comment by dbarrosop** [comment]
I agree, the normalization of the data might be worth discussing as part of the method itself and leave this just as just a wrapper. Could you open an issue in `napalm-base` for discussion?

**Comment by jedelman8** [comment]
Ahhh and to think I almost had a quick and easy PR :)

**Comment by mirceaulinic** [comment]
Doesn't Ansible have a way to re-use stuff, in particular the authentication part? I see tons of redundant code, basically https://github.com/napalm-automation/napalm-ansible/blob/master/library/napalm_get_facts.py#L137-L200 is repeated in each and every module. #justasking

**Comment by jedelman8** [comment]
This is very common in 3rd party modules.  It could be possible to have a `napalm.py` in module_utils in Ansible, but that shared code then becomes part of Ansible core.  There are pros and cons for each, but in terms of "owning" and maintaining full control, it could make sense to keep as-is.  Will defer to @dbarrosop for comments too.

**Comment by dbarrosop** [comment]
I think the best for reusability would be to ship the common code with `napalm-base`.

**Comment by dbarrosop** [comment]
I am merging this, no point on having this sitting around.

**Pull request merged**
