### PR TITLE
Eliminated the os_choices option for better support of community drivers

### PR DESCRIPTION
**Pull request by ktbyers**
os_choices causes issues as it unnecessarily limits the driver options and requires us to roll the napalm-ansible library just to maintain this list.

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
Makes sense, but anyway to try/expect for maybe an import error? Otherwise it will probably mask import error’s as connection errors.

**Comment by ktbyers** [comment]
@itdependsnetworks Good point, I will move the get_network_driver() call so that it is outside of the current try/except statement (i.e. so the standard NAPALM exception was raised here).

**Comment by dbarrosop** [comment]
Awesome, I don't know why I thought we had done this already :S

**Comment by shibumi** [comment]
Heyho, Can we get this PR applied? Would help us a lot with napalm-aos.

**Comment by ktbyers** [comment]
@shibumi You should be able to just `git clone` the change into your environment (i.e. you already can use it).

**Pull request merged**
