### PR TITLE
Document Updates

### PR DESCRIPTION
**Pull request by eegilbert**
I talked with @dbarrosop and made some minor doc changes and added a tutorial. I'll be adding more as time goes one, but wanted to get a discussion started with this.

### CODE REVIEW

**Comment by dbarrosop** [comment]
I wonder if it would be better to have them here instead:

https://napalm.readthedocs.io/en/latest/tutorials/index.html

And just point there in the README.md file. Most people don't check individual github repos and I wouldn't like people missing out this just because of that.

**Comment by ktbyers** [comment]
Yes, I think it would be better to put it in napalm.readthedocs.io.

I think this is the place you go when reading about NAPALM.

**Comment by eegilbert** [comment]
Hi Guys, I can certainly move it there. I've not used read the docs as a contributor, let me give it a try.

**Comment by dbarrosop** [comment]
Great, I am closing this one in the meantime :) If you need help feel free to ping me on slack or just open a PR against napalm with anything you may have (even if it doesnt work yet) and we can try to guide you there.

Thanks!

**Pull request closed without merging**
