### PR TITLE
More userfriendly errors and easier to add getters

### PR DESCRIPTION
**Pull request by ogenstad**
This makes it a bit easier to add getters, but the main reason is to make it easier to troubleshoot. It picks up on not implemented errors and makes it easier to see which getter is having an error.

Examples:
```
$ ansible-playbook -i hosts napalm-facts2.yml --limit 172.29.52.34

PLAY [network] *****************************************************************

TASK [Get Facts] ***************************************************************
fatal: [172.29.52.34]: FAILED! => {"changed": false, "failed": true, "msg": "The filter bgp_config is not supported in napalm-ios [get_bgp_config()]"}

PLAY RECAP *********************************************************************
172.29.52.34               : ok=0    changed=0    unreachable=0    failed=1
```
Or like this:

```
$ ansible-playbook -i hosts napalm-facts.yml --limit router1

PLAY [network] *****************************************************************

TASK [Get BGP Neighbors] *******************************************************
fatal: [router1]: FAILED! => {"changed": false, "failed": true, "msg": "[facts] cannot retrieve device data: list index out of range"}

PLAY RECAP *********************************************************************
router1                    : ok=0    changed=0    unreachable=0    failed=1
```

The facts issue seems to be an actual bug in napalm-iosxr get_facts(), haven't looked closer at that yet.

### CODE REVIEW

**Comment by dbarrosop** [comment]
I have been meaning to tackle that for a while but I haven't had the time. I was thinking you could do this instead:

```NAPALM_GETTERS=[getter for getter in dir(NetworkDriver) if getter.startwith("get_")```

Something like that should work forever and ever.

**Comment by ogenstad** [comment]
Yes that sounds better. Perhaps also implement some parameter to ignore NotImplementedError so people can use the same list on all devices?

I noticed that there are a few functions like `get_route_to()`, which would be a bit weird in this context. What are your thoughts on that? Perhaps there could be some property or decorator in napalm_base to show which of them are facts getters?

The part which would still need to be updated with this in place is the documentation. If there aren't any plans on submitting the module to the Ansible project it might be better to just point to some page on Readthedocs which could be automatically updated.

**Comment by ogenstad** [comment]
Or perhaps allow arguments like:

``` yaml
   tasks:
     - name: Get Facts
       napalm_get_facts:
         hostname: "{{ mapped_ip }}"
         username: vagrant
         password: vagrant
         dev_os: iosxr
         optional_args: "{{ napalm }}"
         filter:
           - bgp_config
           - facts
           - route_to:
               destination: 172.27.10.12
           - interfaces_ip
```

**Comment by dbarrosop** [comment]
Yeah, I think both ideas are good. Ignoring the notimplemented error should probably return something like `{result: {}, not_implemented: true}` So people can query that in case they need to react to something not being implemented.

**Comment by ogenstad** [comment]
I changed the way the NAPALM_GETTERS list is created and added the not_implemented thing. Can discuss about the naming.

Haven't done anything about sending in a dict instead of a string as an entry in the filter list. Another issue to consider there is if someone wants to look up multiple routes or something else.

**Comment by dbarrosop** [comment]
Maybe you can instead have a `filter_arguments` option instead which is a dictionary. The dictionary can be just passed to the filter as `result = get_func(**filter)`.

> Another issue to consider there is if someone wants to look up multiple routes or something else.

So, another variant/iteration of filter_arguments could be a list of dicts. For example:

```
filter_list:
    - destination: 10.0.0.0/24
    - destination: 10.0.1.0/24
```

And then in the ansible module:

```
if filter_arguments:
    result = {}
    for arg in filter_arguments:
        result[arg] = get_func(**arg) # maybe result could be a list instead
else:
    result[] = get_func()
```

**Comment by ogenstad** [comment]
Did you mean `filter_list` from above to be `filter_arguments`? 

> result[arg] = get_func(**arg) # maybe result could be a list instead

I think result would have to be a list in those cases. Might be strange if it was a list in some cases and a filter in other cases.

```python
if filter is used > 1:
    results[filter] = []
else:
    result[filter] = {}
```
An entry it the list could be a dict with the args as keys and another key for data/value. That would be a way to keep it dynamic. However it doesn't feel that neat to have the data format vary in this way.

Also thought I might rename results['not_implemented'] to results['napalm_not_implemented'].

**Comment by dbarrosop** [comment]
Yeah, forgot this method allows you to run a list of filters. I think it's good as it is now. If we want to implement the other option (one single filter with multiple options) we should probably have a different module for that or this one will just become too complex and hard to use.

**Comment by ogenstad** [comment]
> I think it's good as it is now

Which part do you mean by that? The PR or some of the comments?

**Comment by dbarrosop** [comment]
The PR so if you are good I will merge it.

**Comment by ogenstad** [comment]
Yeah, I think so. The only thing is that if someone tries to set route_to as a filter it won't work. However this will still give an error, just a different error compared to before so it's not that big of an issue.

I think you are right about using a different module if people want to collect info with the same filter twice.

**Pull request merged**
