### PR TITLE
Consolidate duplicated code - Don't Merge

### PR DESCRIPTION
**Pull request by ogenstad**
@ktbyers, @dbarrosop, I think we talked about this in the past. This would need to be cleaned up (and tested) before being merged, the modules won't work now since they refer to variables which are no longer there.

However just looking at this PR the idea of what I was thinking about should be quite clear. I.e. remove duplicated code across the modules and make sure that common things only needs to be updated in one place.

The downside of this is that it would require that the napalm-ansible package is installed. For my part I think installing napalm-ansible should be best practise regardless.

What are your thoughts, is this worth pursuing?

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
I know this will not be a popular opinion and considered heresy within the python community, but what about relative imports?

**Comment by ogenstad** [comment]
I would imagine that relative imports might not work. Not sure how it is with "connection: local", but doesn't Ansible make its own copy of the module elsewhere and run it from there?

**Comment by dbarrosop** [comment]
I think we should try. We could do something like:

```
try:
   from napalm-ansible import blah
except ImportError:
   import blah
```

Not sure if it will work due to what you suggested but we can try. Alternatively we could keep the code in different files and have a Makefile to join the different bits instead of using imports.

**Comment by ogenstad** [comment]
Why would the second "import blah" work? Or do you mean "import ..blah"?

It also comes down to what it is we are trying to avoid. Both the imports and something created by a Makefile would break the current option of just git cloning the repo and pointing to that directory.

**Comment by ktbyers** [comment]
I don't think relative imports will work. It would have to be installed.

I think we should just leave what we have. We don't update this code very often and it only takes a few minutes to update it when we have to. 

*** Though if someone wants to do this and require napalm-ansible be installed that is probably okay also ***

There also is a good chance we will need to expand on our action plugin / make a new plugin to deal with the `network_cli` changes in 2.5. I think we will have to figure out how to set NAPALM-ansible to connection:local if network_cli is specified (assuming this is possible).

**Comment by dbarrosop** [comment]
the concatenation via a makefile can be triggered via a CI job before
running the tests and pushed to the same branch

**Comment by ktbyers** [comment]
@dbarrosop If your comment was in response to mine here, I think we are talking about totally different things (i.e. my comments had nothing to do with testing or CI, but that will break for end-users).

**Comment by dbarrosop** [comment]
I was responding to ogenstad

**Comment by ktbyers** [comment]
@dbarrosop Ooops, okay misunderstood...

**Comment by ktbyers** [comment]
I am going to close as I don't think there is any active work going on with respect to this...if someone starts working on this; they can re-open it or a similar PR.

**Pull request closed without merging**
