### PR TITLE
added archive running option napalm_install_config module

### PR DESCRIPTION
**Pull request by benmaddison**
Added `archive_file` module option to the `napalm_install_config` module which, when set, retrieves the current running-config of the device using `driver.get_config(retrieve="running")` and saves the output to the given path.
This method is faster and more reliable than the equivalent method of setting a fact using `napalm_get_facts` and then writing to a file using the `copy` module, as ansible obfuscates strings in the output that match private connection variables, which can render the archived file unreadable.

### CODE REVIEW

**Comment by dbarrosop** [comment]
Great idea, I think this certainly makes sense. Thanks!

**Comment by ktbyers** [comment]
I was thinking we might want to add a revision history onto this (i.e. a second Ansible argument like `archive_revisions` where the value is a number. This would add a `-1`, `-2`, `-n` to the file name (in some way) up to the number specified.

This would help avoid the problem of running playbook twice blowing away the archive you wanted to keep.

**Comment by dbarrosop** [comment]
I figured that was an application issue, meaning that people could do something like:

`archive_file: "/some/path/{{ inventory_hostname}}-{{ timestamp_or_other_preferred_method }}`

In my opinion the `file` prefix implies we are dealing with a file, not with a folder or hierarchy where we may be handling some logic to rotate previous archives. What do you think?

**Comment by ktbyers** [comment]
Yeah, good point...that works for me.

**Comment by benmaddison** [comment]
I agree. We'll be archiving these to a git sub-repo, which would then get committed later in the play - so a baked-in mechanism to add version numbers would just add complications.

**Pull request merged**
