### PR TITLE
napalm-ansible release 0.7.1

### PR DESCRIPTION
**Pull request by ktbyers**
Add support for nxos_ssh option.

### CODE REVIEW

**Comment by dbarrosop** [comment]
tests for ansible2.4 are failing

**Comment by ktbyers** [comment]
@dbarrosop Let me check what happened.

**Comment by ktbyers** [comment]
I think this has to do with our variable naming on the register of 'napalm_facts' i.e. that we are using the same name here as what we use for saving ansible facts.

Will dig into it some more and fix.

**Review by dbarrosop — APPROVED** [review]

**Comment by dbarrosop** [comment]
Nice!

**Pull request merged**
